// Generated by scripts/build-gallery-data.mjs. Do not edit by hand.
export const sections = [
  {
    "id": "glen-ellen-preserve",
    "title": "Glen Ellen Preserve",
    "range": "Jun 21, 2026",
    "note": "#animals #nature",
    "tags": [
      "animals",
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21--barbed-wire-fence--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Barbed Wire Fence",
        "title": "Barbed Wire Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-not--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire Not",
        "title": "Barbed Wire Not",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-on-fence--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire On Fence",
        "title": "Barbed Wire On Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-bird-on-the-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Bird On The Fence",
        "title": "Bird On The Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-blue-flowers--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Blue Flowers",
        "title": "Blue Flowers",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-lizard-on-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Lizard On Fence",
        "title": "Lizard On Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-portrait-of-a-purple-flower--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Portrait Of A Purple Flower",
        "title": "Portrait Of A Purple Flower",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      }
    ]
  }
];
