// Generated by scripts/build-gallery-data.mjs. Do not edit by hand.
export const sections = [
  {
    "id": "cloverdale-campsite",
    "title": "Cloverdale Campsite",
    "range": "Jul 4, 2026",
    "note": "#nature",
    "tags": [
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-artichoke-in-bloom--nature.jpeg",
        "width": 768,
        "height": 1024,
        "alt": "Artichoke In Bloom",
        "title": "Artichoke In Bloom",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-campsite-grill--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Campsite Grill",
        "title": "Campsite Grill",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-moss-hanging-from-tree--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Moss Hanging From Tree",
        "title": "Moss Hanging From Tree",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-white-flower--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "White Flower",
        "title": "White Flower",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      }
    ]
  },
  {
    "id": "glen-ellen-preserve",
    "title": "Glen Ellen Preserve",
    "range": "Jun 21, 2026",
    "note": "#animals #nature",
    "tags": [
      "animals",
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21--barbed-wire-fence--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Barbed Wire Fence",
        "title": "Barbed Wire Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-not--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire Not",
        "title": "Barbed Wire Not",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-on-fence--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire On Fence",
        "title": "Barbed Wire On Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-bird-on-the-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Bird On The Fence",
        "title": "Bird On The Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-blue-flowers--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Blue Flowers",
        "title": "Blue Flowers",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-lizard-on-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Lizard On Fence",
        "title": "Lizard On Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-portrait-of-a-purple-flower--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Portrait Of A Purple Flower",
        "title": "Portrait Of A Purple Flower",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      }
    ]
  },
  {
    "id": "petaluma-farm",
    "title": "Petaluma Farm",
    "range": "Sep 12, 2025 - Sep 14, 2025",
    "note": "#animals #family #nature",
    "tags": [
      "animals",
      "family",
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/petaluma-farm/2025-09-12-brother-and-sister-goats--nature--animals.jpeg",
        "width": 2364,
        "height": 1330,
        "alt": "Brother And Sister Goats",
        "title": "Brother And Sister Goats",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2025-09-12",
        "dateLabel": "Sep 12, 2025",
        "tone": "blue"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-12-lavendar-in-the-garden--nature.jpeg",
        "width": 638,
        "height": 360,
        "alt": "Lavendar In The Garden",
        "title": "Lavendar In The Garden",
        "tags": [
          "nature"
        ],
        "date": "2025-09-12",
        "dateLabel": "Sep 12, 2025",
        "tone": "green"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-12-walle-magestical-pose--family.jpeg",
        "width": 2364,
        "height": 1330,
        "alt": "Walle Magestical Pose",
        "title": "Walle Magestical Pose",
        "tags": [
          "family"
        ],
        "date": "2025-09-12",
        "dateLabel": "Sep 12, 2025",
        "tone": "soft"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-13--fenced-in-goats--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Fenced In Goats",
        "title": "Fenced In Goats",
        "tags": [
          "nature"
        ],
        "date": "2025-09-13",
        "dateLabel": "Sep 13, 2025",
        "tone": "green"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-13-goat-behind-fence--nature--animals.jpeg",
        "width": 2364,
        "height": 1330,
        "alt": "Goat Behind Fence",
        "title": "Goat Behind Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2025-09-13",
        "dateLabel": "Sep 13, 2025",
        "tone": "blue"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-13-goat-saying-hellow--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Goat Saying Hellow",
        "title": "Goat Saying Hellow",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2025-09-13",
        "dateLabel": "Sep 13, 2025",
        "tone": "blue"
      },
      {
        "src": "/photos/petaluma-farm/2025-09-14-skyward-pink%20bottlebrush--nature.jpeg",
        "width": 638,
        "height": 360,
        "alt": "Skyward Pink Bottlebrush",
        "title": "Skyward Pink Bottlebrush",
        "tags": [
          "nature"
        ],
        "date": "2025-09-14",
        "dateLabel": "Sep 14, 2025",
        "tone": "green"
      }
    ]
  }
];
