// Generated by scripts/build-gallery-data.mjs. Do not edit by hand.
export const sections = [
  {
    "id": "cloverdale-campsite",
    "title": "Cloverdale Campsite",
    "range": "Jul 4, 2026 - Jul 4, 2027",
    "note": "#nature",
    "tags": [
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-artichoke-in-bloom--nature.jpeg",
        "width": 768,
        "height": 1024,
        "alt": "Artichoke In Bloom",
        "title": "Artichoke In Bloom",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-moss-hanging-from-tree--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Moss Hanging From Tree",
        "title": "Moss Hanging From Tree",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2026-07-04-white-flower--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "White Flower",
        "title": "White Flower",
        "tags": [
          "nature"
        ],
        "date": "2026-07-04",
        "dateLabel": "Jul 4, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/cloverdale-campsite/2027-07-04-campsite-grill--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Campsite Grill",
        "title": "Campsite Grill",
        "tags": [
          "nature"
        ],
        "date": "2027-07-04",
        "dateLabel": "Jul 4, 2027",
        "tone": "green"
      }
    ]
  },
  {
    "id": "glen-ellen-preserve",
    "title": "Glen Ellen Preserve",
    "range": "Jun 21, 2026",
    "note": "#animals #nature",
    "tags": [
      "animals",
      "nature"
    ],
    "photos": [
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21--barbed-wire-fence--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Barbed Wire Fence",
        "title": "Barbed Wire Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-not--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire Not",
        "title": "Barbed Wire Not",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-barbed-wire-on-fence--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Barbed Wire On Fence",
        "title": "Barbed Wire On Fence",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-bird-on-the-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Bird On The Fence",
        "title": "Bird On The Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-blue-flowers--nature.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Blue Flowers",
        "title": "Blue Flowers",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-lizard-on-fence--nature--animals.jpeg",
        "width": 1182,
        "height": 665,
        "alt": "Lizard On Fence",
        "title": "Lizard On Fence",
        "tags": [
          "nature",
          "animals"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "blue"
      },
      {
        "src": "/photos/glen-ellen-preserve/2026-06-21-portrait-of-a-purple-flower--nature.jpeg",
        "width": 665,
        "height": 1182,
        "alt": "Portrait Of A Purple Flower",
        "title": "Portrait Of A Purple Flower",
        "tags": [
          "nature"
        ],
        "date": "2026-06-21",
        "dateLabel": "Jun 21, 2026",
        "tone": "green"
      }
    ]
  }
];
